html = """<li><a href="/ebooks/32854">Arsène Lupin, gentleman-cambrioleur by Maurice Leblanc (218)</a></li>
<li><a href="/ebooks/64322">Les conséquences politiques de la paix by Jacques Bainville (164)</a></li>
<li><a href="/ebooks/57775">Le jardin des supplices by Octave Mirbeau (96)</a></li>
<li><a href="/ebooks/17489">Les misérables Tome I: Fantine by Victor Hugo (49)</a></li>
<li><a href="/ebooks/64305">Chair by Eugène Montfort (47)</a></li>
<li><a href="/ebooks/17989">Le comte de Monte-Cristo, Tome I by Alexandre Dumas (41)</a></li>
<li><a href="/ebooks/16816">Le roman de la rose - Tome I by active 1230 de Lorris Guillaume and de Meun Jean (36)</a></li>
<li><a href="/ebooks/2650">Du côté de chez Swann by Marcel Proust (31)</a></li>
<li><a href="/ebooks/14155">Madame Bovary by Gustave Flaubert (30)</a></li>
<li><a href="/ebooks/6099">Les Fleurs du Mal by Charles Baudelaire (29)</a></li>
<li><a href="/ebooks/56327">Fables de La Fontaine by Jean de La Fontaine (27)</a></li>
<li><a href="/ebooks/13951">Les trois mousquetaires by Alexandre Dumas (27)</a></li>
<li><a href="/ebooks/14287">L'île mystérieuse by Jules Verne (26)</a></li>
<li><a href="/ebooks/798">Le rouge et le noir: chronique du XIXe siècle by Stendhal (23)</a></li>
<li><a href="/ebooks/27035">Entretiens / Interviews / Entrevistas by Marie Lebert (23)</a></li>
<li><a href="/ebooks/64290">Paysages Passionnés by Gabriel Faure (22)</a></li>
<li><a href="/ebooks/19657">Notre-Dame de Paris by Victor Hugo (21)</a></li>
<li><a href="/ebooks/39765">Les français peints par eux-mêmes, tome 1 (21)</a></li>
<li><a href="/ebooks/18244">Contes merveilleux, Tome I by H. C.  Andersen (21)</a></li>
<li><a href="/ebooks/4650">Candide, ou, L'optimisme by Voltaire (21)</a></li>
<li><a href="/ebooks/52006">Les liaisons dangereuses by Choderlos de Laclos (20)</a></li>
<li><a href="/ebooks/60347">Les Français peints par eux-mêmes, tome 2 (19)</a></li>
<li><a href="/ebooks/5781">Le Grand Meaulnes by Alain-Fournier (19)</a></li>
<li><a href="/ebooks/10746">Boule de Suif by Guy de Maupassant (19)</a></li>
<li><a href="/ebooks/10775">Le Horla by Guy de Maupassant (19)</a></li>
<li><a href="/ebooks/41211">La Comédie humaine - Volume 01 by Honoré de Balzac (19)</a></li>
<li><a href="/ebooks/7461">Thérèse Raquin by Émile Zola (18)</a></li>
<li><a href="/ebooks/45119">Œuvres complètes de Guy de Maupassant - volume 01 by Guy de Maupassant (18)</a></li>
<li><a href="/ebooks/13846">Discours de la méthode by René Descartes (18)</a></li>
<li><a href="/ebooks/800">Le tour du monde en quatre-vingts jours by Jules Verne (18)</a></li>
<li><a href="/ebooks/5423">L'homme Qui Rit by Victor Hugo (17)</a></li>
<li><a href="/ebooks/17494">Les misérables Tome III: Marius by Victor Hugo (17)</a></li>
<li><a href="/ebooks/20761">Histoires extraordinaires by Edgar Allan Poe (17)</a></li>
<li><a href="/ebooks/60746">Le capitaine Fracasse by Théophile Gautier (17)</a></li>
<li><a href="/ebooks/56668">Une saison en enfer by Arthur Rimbaud (17)</a></li>
<li><a href="/ebooks/18143">Romeo and Juliet. French by William Shakespeare (17)</a></li>
<li><a href="/ebooks/44070">Le ménagier de Paris (v. 1 & 2) by Anonymous (16)</a></li>
<li><a href="/ebooks/57584">The Book of the Homeless (Le livre des sans-foyer) (16)</a></li>
<li><a href="/ebooks/35971">Traité élémentaire de la peinture, by da Vinci Leonardo (16)</a></li>
<li><a href="/ebooks/36780">Lettres de mon moulin by Alphonse Daudet (16)</a></li>
<li><a href="/ebooks/55456">Alice's adventures in Wonderland. French by Lewis Carroll (16)</a></li>
<li><a href="/ebooks/28891">Le Cabinet des Fées (15)</a></li>
<li><a href="/ebooks/6484">Chéri by Colette (14)</a></li>
<li><a href="/ebooks/12246">Œuvres complètes de François Villon by François Villon (14)</a></li>
<li><a href="/ebooks/36528">Monsieur Vénus by Rachilde (14)</a></li>
<li><a href="/ebooks/12005">Les Chants de Maldoror by comte de Lautréamont (14)</a></li>
<li><a href="/ebooks/64289">Jean Sbogar by Charles Nodier (14)</a></li>
<li><a href="/ebooks/12137">La Légende des Siècles by Victor Hugo (14)</a></li>
<li><a href="/ebooks/5097">Vingt mille Lieues Sous Les Mers — Complete by Jules Verne (13)</a></li>
<li><a href="/ebooks/17980">Les caractères by Jean de La Bruyère (13)</a></li>
<li><a href="/ebooks/18245">Contes merveilleux, Tome II by H. C.  Andersen (13)</a></li>
<li><a href="/ebooks/17518">Les misérables Tome IV: L'idylle rue Plumet et l'épopée rue Saint-Denis by Victor Hugo (13)</a></li>
<li><a href="/ebooks/26608">Le trésor de la cité des dames de degré en degré et de tous estatz by de Pisan Christine (13)</a></li>
<li><a href="/ebooks/56149">A rebours by J.-K.  Huysmans (13)</a></li>
<li><a href="/ebooks/40248">Voyage autour de ma chambre by Xavier de Maistre (13)</a></li>
<li><a href="/ebooks/5711">Germinal by Émile Zola (13)</a></li>
<li><a href="/ebooks/26812">Un coeur simple by Gustave Flaubert (13)</a></li>
<li><a href="/ebooks/60450">Les naufragés du Jonathan by Jules Verne (13)</a></li>
<li><a href="/ebooks/37989">Lettres d'un voyageur by George Sand (12)</a></li>
<li><a href="/ebooks/14163">Les enfants du capitaine Grant by Jules Verne (12)</a></li>
<li><a href="/ebooks/12949">Contes Français (12)</a></li>
<li><a href="/ebooks/4791">Voyage au Centre de la Terre by Jules Verne (12)</a></li>
<li><a href="/ebooks/13952">Vingt ans après by Alexandre Dumas (12)</a></li>
<li><a href="/ebooks/14082">The Raven. by Edgar Allan Poe (12)</a></li>
<li><a href="/ebooks/22741">Physiologie du goût by Brillat-Savarin (12)</a></li>
<li><a href="/ebooks/11748">French Conversation and Composition by Harry Vincent Wann (12)</a></li>
<li><a href="/ebooks/14158">On the origin of species. French by Charles Darwin (12)</a></li>
<li><a href="/ebooks/1339">Salomé by Oscar Wilde (12)</a></li>
<li><a href="/ebooks/11049">Eugénie Grandet by Honoré de Balzac (12)</a></li>
<li><a href="/ebooks/44354">Dictionnaire de nos fautes contre la langue française by Raoul Rinfret (12)</a></li>
<li><a href="/ebooks/62215">Le Fantôme de l'Opéra by Gaston Leroux (12)</a></li>
<li><a href="/ebooks/35019">Le diable boiteux, tome I by Alain René Le Sage (11)</a></li>
<li><a href="/ebooks/6838">Le Dernier Jour d'un Condamné by Victor Hugo (11)</a></li>
<li><a href="/ebooks/13950">Le vicomte de Bragelonne, Tome IV. by Alexandre Dumas (11)</a></li>
<li><a href="/ebooks/59926">Le blé en herbe: roman by Colette (11)</a></li>
<li><a href="/ebooks/5250">Nana by Émile Zola (11)</a></li>
<li><a href="/ebooks/63804">L'esprit dans l'histoire: Recherches et curiosités sur les mots historiques by Edouard Fournier (11)</a></li>
<li><a href="/ebooks/29302">Poésies complètes, by Arthur Rimbaud (11)</a></li>
<li><a href="/ebooks/12230">Œuvres de Napoléon Bonaparte, Tome I. by Emperor of the French Napoleon I (11)</a></li>
<li><a href="/ebooks/48852">Le parler populaire des Canadiens français by N.-E.  Dionne (11)</a></li>
<li><a href="/ebooks/16240">La Vénus d'Ille by Prosper Mérimée (11)</a></li>
<li><a href="/ebooks/17457">Une vie by Guy de Maupassant (11)</a></li>
<li><a href="/ebooks/28718">Les crimes de l'amour by marquis de Sade (11)</a></li>
<li><a href="/ebooks/61239">Contes pour les bibliophiles by Octave Uzanne (11)</a></li>
<li><a href="/ebooks/14609">Kamasutra. by Vatsyayana (11)</a></li>
<li><a href="/ebooks/55569">Calligrammes: Poèmes de la paix et de la guerre (1913-1916) by Guillaume Apollinaire (10)</a></li>
<li><a href="/ebooks/15462">Alcools by Guillaume Apollinaire (10)</a></li>
<li><a href="/ebooks/36708">Soeur Thérèse de l'Enfant-Jésus et de la Sainte Face by Saint de Lisieux Thérèse (10)</a></li>
<li><a href="/ebooks/21013">Histoire de la magie by Éliphas Lévi (10)</a></li>
<li><a href="/ebooks/23654">Mémoires d'Outre-Tombe, Tome 2 by vicomte de François-René Chateaubriand (10)</a></li>
<li><a href="/ebooks/26400">La géométrie by René Descartes (10)</a></li>
<li><a href="/ebooks/4647">Zadig, ou la Destinée, histoire orientale by Voltaire (10)</a></li>
<li><a href="/ebooks/17708">Gaspard de la nuit: Fantaisies à la manière de Rembrandt et de Callot by Aloysius Bertrand (10)</a></li>
<li><a href="/ebooks/11714">Contes de la Becasse by Guy de Maupassant (10)</a></li>
<li><a href="/ebooks/17493">Les misérables Tome II: Cosette by Victor Hugo (10)</a></li>
<li><a href="/ebooks/4548">Cinq Semaines En Ballon by Jules Verne (10)</a></li>
<li><a href="/ebooks/54873">Vingt mille lieues sous les mers by Jules Verne (10)</a></li>
<li><a href="/ebooks/13947">Le vicomte de Bragelonne, Tome I. by Alexandre Dumas (10)</a></li>
<li><a href="/ebooks/48529">Essais de Montaigne (self-édition) - Volume I by Michel de Montaigne (10)</a></li>
<li><a href="/ebooks/16883">Les amours jaunes by Tristan Corbière (10)</a></li>"""

with open("data/resources/top100-fr.txt","w",encoding="utf-8") as f:
    lines = html.split("\n")
    for line in lines:
        if line.startswith("<li><a href="):
            url = line.split('"')[1]
            id = url.split("/")[-1]
            print(f"{id}")
            f.write(f"{id}\n")


